import type { SteamMarketItem } from "./types";

export const mockItems: SteamMarketItem[] = [
  {
    name: "Hazmat Suit",
    slug: "hazmat-suit",
    description: "A bright yellow hazmat suit offering full-body protection. Popular among new players exploring hazardous zones.",
    type: "character",
    rarity: "uncommon",
    imageUrl: "/items/hazmat-suit.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Hazmat%20Suit",
    currentPrice: 4.52,
    lowestPrice: 3.10,
    medianPrice: 4.00,
    volume: 87,
    priceChange24h: 2.35,
    isLimited: false,
  },
  {
    name: "Crimson Operative",
    slug: "crimson-operative",
    description: "A sleek red tactical outfit favored by veteran players. Features subtle armor plating details.",
    type: "character",
    rarity: "rare",
    imageUrl: "/items/crimson-operative.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Crimson%20Operative",
    currentPrice: 12.75,
    lowestPrice: 8.50,
    medianPrice: 11.20,
    volume: 34,
    priceChange24h: -1.50,
    isLimited: false,
  },
  {
    name: "Neon Runner Jacket",
    slug: "neon-runner-jacket",
    description: "A cyberpunk-inspired jacket with glowing neon trim. Stands out in any environment.",
    type: "clothing",
    rarity: "rare",
    imageUrl: "/items/neon-runner-jacket.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Neon%20Runner%20Jacket",
    currentPrice: 8.30,
    lowestPrice: 5.75,
    medianPrice: 7.50,
    volume: 56,
    priceChange24h: 5.20,
    isLimited: false,
  },
  {
    name: "Golden Skull Mask",
    slug: "golden-skull-mask",
    description: "A legendary golden skull mask that strikes fear into opponents. Extremely rare drop from Halloween events.",
    type: "accessory",
    rarity: "legendary",
    imageUrl: "/items/golden-skull-mask.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Golden%20Skull%20Mask",
    currentPrice: 45.00,
    lowestPrice: 30.00,
    medianPrice: 38.50,
    volume: 5,
    priceChange24h: 8.75,
    isLimited: true,
  },
  {
    name: "Desert Camo Pants",
    slug: "desert-camo-pants",
    description: "Standard-issue desert camouflage pants. Practical and affordable.",
    type: "clothing",
    rarity: "common",
    imageUrl: "/items/desert-camo-pants.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Desert%20Camo%20Pants",
    currentPrice: 0.45,
    lowestPrice: 0.20,
    medianPrice: 0.35,
    volume: 234,
    priceChange24h: -0.80,
    isLimited: false,
  },
  {
    name: "Arctic Explorer",
    slug: "arctic-explorer",
    description: "A full winter exploration outfit with fur-lined hood. Built for cold weather maps.",
    type: "character",
    rarity: "uncommon",
    imageUrl: "/items/arctic-explorer.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Arctic%20Explorer",
    currentPrice: 3.20,
    lowestPrice: 2.00,
    medianPrice: 2.80,
    volume: 112,
    priceChange24h: 1.10,
    isLimited: false,
  },
  {
    name: "Plasma Blade",
    slug: "plasma-blade",
    description: "A futuristic energy blade with a glowing blue edge. One of the most sought-after weapon skins.",
    type: "weapon",
    rarity: "legendary",
    imageUrl: "/items/plasma-blade.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Plasma%20Blade",
    currentPrice: 32.50,
    lowestPrice: 22.00,
    medianPrice: 28.00,
    volume: 12,
    priceChange24h: 3.40,
    isLimited: true,
  },
  {
    name: "Street Punk Hoodie",
    slug: "street-punk-hoodie",
    description: "A graffiti-covered black hoodie with a rebellious street art design.",
    type: "clothing",
    rarity: "uncommon",
    imageUrl: "/items/street-punk-hoodie.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Street%20Punk%20Hoodie",
    currentPrice: 2.15,
    lowestPrice: 1.50,
    medianPrice: 1.90,
    volume: 145,
    priceChange24h: -2.10,
    isLimited: false,
  },
  {
    name: "Tactical Visor",
    slug: "tactical-visor",
    description: "A high-tech heads-up display visor with augmented reality overlay effects.",
    type: "accessory",
    rarity: "rare",
    imageUrl: "/items/tactical-visor.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Tactical%20Visor",
    currentPrice: 9.80,
    lowestPrice: 6.25,
    medianPrice: 8.40,
    volume: 28,
    priceChange24h: 4.50,
    isLimited: false,
  },
  {
    name: "Rustic Work Boots",
    slug: "rustic-work-boots",
    description: "Worn leather work boots. Nothing fancy, but they get the job done.",
    type: "clothing",
    rarity: "common",
    imageUrl: "/items/rustic-work-boots.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Rustic%20Work%20Boots",
    currentPrice: 0.25,
    lowestPrice: 0.10,
    medianPrice: 0.20,
    volume: 312,
    priceChange24h: 0.50,
    isLimited: false,
  },
  {
    name: "Shadow Ops",
    slug: "shadow-ops",
    description: "An all-black tactical outfit with night vision goggles. Perfect for stealth gameplay.",
    type: "character",
    rarity: "rare",
    imageUrl: "/items/shadow-ops.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Shadow%20Ops",
    currentPrice: 15.40,
    lowestPrice: 10.00,
    medianPrice: 13.00,
    volume: 22,
    priceChange24h: -3.20,
    isLimited: false,
  },
  {
    name: "Christmas Sweater",
    slug: "christmas-sweater",
    description: "A festive ugly Christmas sweater with pixelated reindeer. 2024 holiday exclusive.",
    type: "clothing",
    rarity: "legendary",
    imageUrl: "/items/christmas-sweater.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Christmas%20Sweater",
    currentPrice: 28.90,
    lowestPrice: 15.00,
    medianPrice: 22.00,
    volume: 8,
    priceChange24h: 12.50,
    isLimited: true,
  },
  {
    name: "Cargo Shorts",
    slug: "cargo-shorts",
    description: "Basic khaki cargo shorts with plenty of pockets. The default casual look.",
    type: "clothing",
    rarity: "common",
    imageUrl: "/items/cargo-shorts.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Cargo%20Shorts",
    currentPrice: 0.15,
    lowestPrice: 0.05,
    medianPrice: 0.12,
    volume: 456,
    priceChange24h: -1.20,
    isLimited: false,
  },
  {
    name: "Mech Pilot Suit",
    slug: "mech-pilot-suit",
    description: "A reinforced pilot suit designed for heavy mech operation. Features integrated HUD elements.",
    type: "character",
    rarity: "legendary",
    imageUrl: "/items/mech-pilot-suit.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Mech%20Pilot%20Suit",
    currentPrice: 52.00,
    lowestPrice: 35.00,
    medianPrice: 44.00,
    volume: 3,
    priceChange24h: 6.80,
    isLimited: true,
  },
  {
    name: "Bandana",
    slug: "bandana",
    description: "A simple cloth bandana worn over the face. Available in multiple colors.",
    type: "accessory",
    rarity: "common",
    imageUrl: "/items/bandana.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Bandana",
    currentPrice: 0.35,
    lowestPrice: 0.15,
    medianPrice: 0.28,
    volume: 198,
    priceChange24h: 0.00,
    isLimited: false,
  },
  {
    name: "Samurai Armor",
    slug: "samurai-armor",
    description: "Traditional Japanese samurai armor with a modern twist. Includes ornate shoulder guards.",
    type: "character",
    rarity: "rare",
    imageUrl: "/items/samurai-armor.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Samurai%20Armor",
    currentPrice: 18.25,
    lowestPrice: 12.00,
    medianPrice: 15.50,
    volume: 16,
    priceChange24h: 2.90,
    isLimited: false,
  },
  {
    name: "Utility Belt",
    slug: "utility-belt",
    description: "A multi-purpose utility belt with various pouches and tool holders.",
    type: "accessory",
    rarity: "uncommon",
    imageUrl: "/items/utility-belt.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Utility%20Belt",
    currentPrice: 1.80,
    lowestPrice: 1.00,
    medianPrice: 1.50,
    volume: 89,
    priceChange24h: -0.60,
    isLimited: false,
  },
  {
    name: "Riot Shield",
    slug: "riot-shield",
    description: "A transparent polycarbonate riot shield. Provides intimidating presence in-game.",
    type: "weapon",
    rarity: "uncommon",
    imageUrl: "/items/riot-shield.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Riot%20Shield",
    currentPrice: 3.75,
    lowestPrice: 2.25,
    medianPrice: 3.00,
    volume: 67,
    priceChange24h: 1.80,
    isLimited: false,
  },
  {
    name: "Aviator Sunglasses",
    slug: "aviator-sunglasses",
    description: "Classic gold-framed aviator sunglasses. Cool never goes out of style.",
    type: "accessory",
    rarity: "uncommon",
    imageUrl: "/items/aviator-sunglasses.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Aviator%20Sunglasses",
    currentPrice: 2.50,
    lowestPrice: 1.50,
    medianPrice: 2.10,
    volume: 76,
    priceChange24h: 3.00,
    isLimited: false,
  },
  {
    name: "Viking Raider",
    slug: "viking-raider",
    description: "A fearsome Viking warrior outfit with horned helmet and fur cape.",
    type: "character",
    rarity: "rare",
    imageUrl: "/items/viking-raider.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Viking%20Raider",
    currentPrice: 11.00,
    lowestPrice: 7.50,
    medianPrice: 9.50,
    volume: 41,
    priceChange24h: -0.90,
    isLimited: false,
  },
  {
    name: "Lab Coat",
    slug: "lab-coat",
    description: "A clean white laboratory coat. Makes you look like a scientist... or a mad one.",
    type: "clothing",
    rarity: "common",
    imageUrl: "/items/lab-coat.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Lab%20Coat",
    currentPrice: 0.55,
    lowestPrice: 0.30,
    medianPrice: 0.45,
    volume: 167,
    priceChange24h: 1.50,
    isLimited: false,
  },
  {
    name: "Dragon Scale Gauntlets",
    slug: "dragon-scale-gauntlets",
    description: "Ornate gauntlets crafted from dragon scales. Glows with an inner fire effect.",
    type: "accessory",
    rarity: "legendary",
    imageUrl: "/items/dragon-scale-gauntlets.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Dragon%20Scale%20Gauntlets",
    currentPrice: 38.00,
    lowestPrice: 25.00,
    medianPrice: 32.00,
    volume: 7,
    priceChange24h: 5.60,
    isLimited: true,
  },
  {
    name: "Mechanic Overalls",
    slug: "mechanic-overalls",
    description: "Grease-stained blue mechanic overalls. Practical workwear for the hands-on player.",
    type: "clothing",
    rarity: "common",
    imageUrl: "/items/mechanic-overalls.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Mechanic%20Overalls",
    currentPrice: 0.40,
    lowestPrice: 0.18,
    medianPrice: 0.32,
    volume: 203,
    priceChange24h: -0.40,
    isLimited: false,
  },
  {
    name: "Cyber Katana",
    slug: "cyber-katana",
    description: "A high-frequency blade with glowing circuit patterns along the edge.",
    type: "weapon",
    rarity: "rare",
    imageUrl: "/items/cyber-katana.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Cyber%20Katana",
    currentPrice: 14.60,
    lowestPrice: 9.00,
    medianPrice: 12.00,
    volume: 25,
    priceChange24h: 7.30,
    isLimited: false,
  },
  {
    name: "Space Explorer",
    slug: "space-explorer",
    description: "A full astronaut suit with reflective visor and life support backpack.",
    type: "character",
    rarity: "uncommon",
    imageUrl: "/items/space-explorer.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Space%20Explorer",
    currentPrice: 5.80,
    lowestPrice: 3.50,
    medianPrice: 4.90,
    volume: 63,
    priceChange24h: 0.70,
    isLimited: false,
  },
  {
    name: "Pirate Captain",
    slug: "pirate-captain",
    description: "A swashbuckling pirate captain outfit with tricorn hat, eyepatch, and coat.",
    type: "character",
    rarity: "rare",
    imageUrl: "/items/pirate-captain.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Pirate%20Captain",
    currentPrice: 10.20,
    lowestPrice: 6.50,
    medianPrice: 8.80,
    volume: 38,
    priceChange24h: -1.80,
    isLimited: false,
  },
  {
    name: "Steampunk Goggles",
    slug: "steampunk-goggles",
    description: "Brass-plated goggles with multiple magnification lenses. Victorian engineering meets gaming.",
    type: "accessory",
    rarity: "uncommon",
    imageUrl: "/items/steampunk-goggles.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Steampunk%20Goggles",
    currentPrice: 2.90,
    lowestPrice: 1.75,
    medianPrice: 2.40,
    volume: 82,
    priceChange24h: 1.30,
    isLimited: false,
  },
  {
    name: "Rusty Machete",
    slug: "rusty-machete",
    description: "A well-worn machete with a rusty blade. Common but effective.",
    type: "weapon",
    rarity: "common",
    imageUrl: "/items/rusty-machete.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Rusty%20Machete",
    currentPrice: 0.60,
    lowestPrice: 0.25,
    medianPrice: 0.45,
    volume: 178,
    priceChange24h: -0.50,
    isLimited: false,
  },
  {
    name: "Halloween Pumpkin Head",
    slug: "halloween-pumpkin-head",
    description: "A carved jack-o-lantern worn as a helmet. Glows eerily in the dark. 2024 Halloween event exclusive.",
    type: "accessory",
    rarity: "legendary",
    imageUrl: "/items/halloween-pumpkin-head.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Halloween%20Pumpkin%20Head",
    currentPrice: 22.50,
    lowestPrice: 12.00,
    medianPrice: 18.00,
    volume: 11,
    priceChange24h: 15.20,
    isLimited: true,
  },
  {
    name: "Military Fatigues",
    slug: "military-fatigues",
    description: "Standard green military combat fatigues. A classic tactical look.",
    type: "clothing",
    rarity: "common",
    imageUrl: "/items/military-fatigues.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Military%20Fatigues",
    currentPrice: 0.50,
    lowestPrice: 0.22,
    medianPrice: 0.38,
    volume: 245,
    priceChange24h: 0.30,
    isLimited: false,
  },
  {
    name: "Neon Wireframe",
    slug: "neon-wireframe",
    description: "A character skin rendered entirely in glowing wireframe. Unique visual effect that stands out.",
    type: "character",
    rarity: "legendary",
    imageUrl: "/items/neon-wireframe.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Neon%20Wireframe",
    currentPrice: 41.00,
    lowestPrice: 28.00,
    medianPrice: 35.00,
    volume: 4,
    priceChange24h: 9.20,
    isLimited: true,
  },
  {
    name: "Leather Gloves",
    slug: "leather-gloves",
    description: "Simple brown leather gloves. Keeps your hands warm and your grip firm.",
    type: "accessory",
    rarity: "common",
    imageUrl: "/items/leather-gloves.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Leather%20Gloves",
    currentPrice: 0.30,
    lowestPrice: 0.12,
    medianPrice: 0.25,
    volume: 267,
    priceChange24h: -0.20,
    isLimited: false,
  },
  {
    name: "Trench Coat",
    slug: "trench-coat",
    description: "A long black trench coat with a mysterious aura. Popular in roleplay servers.",
    type: "clothing",
    rarity: "uncommon",
    imageUrl: "/items/trench-coat.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Trench%20Coat",
    currentPrice: 3.40,
    lowestPrice: 2.00,
    medianPrice: 2.80,
    volume: 95,
    priceChange24h: 2.00,
    isLimited: false,
  },
  {
    name: "Compound Bow",
    slug: "compound-bow",
    description: "A modern compound bow with carbon fiber limbs. Silent and deadly.",
    type: "weapon",
    rarity: "uncommon",
    imageUrl: "/items/compound-bow.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Compound%20Bow",
    currentPrice: 4.10,
    lowestPrice: 2.50,
    medianPrice: 3.50,
    volume: 53,
    priceChange24h: -1.40,
    isLimited: false,
  },
  {
    name: "Firefighter Helmet",
    slug: "firefighter-helmet",
    description: "A bright red firefighter helmet with face shield. Hero vibes only.",
    type: "accessory",
    rarity: "uncommon",
    imageUrl: "/items/firefighter-helmet.png",
    marketUrl: "https://steamcommunity.com/market/listings/590830/Firefighter%20Helmet",
    currentPrice: 1.95,
    lowestPrice: 1.20,
    medianPrice: 1.60,
    volume: 104,
    priceChange24h: 0.80,
    isLimited: false,
  },
];
